version: 2
updates:
# Fetch and update latest `npm` packages
- package-ecosystem: npm
  directory: '/'
  schedule:
    interval: daily
    time: '00:00'
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
  schedule:
    interval: daily
    time: '00:00'
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope